In [1]:
import numpy as np 
cars = np.array(['chevrolet chevelle malivu','buick skylark 320','playmouth satellelite','amc rebel sst','frod torino'])
cars[1]



'buick skylark 320'

In [7]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("median horsepower = ",np.median(horsepower_arr))

median horsepower =  150.0


In [6]:
import numpy as np
student_name = ['ram', 'sihi', 'kruti', 'vedha']
student_marks=([42,48],[76,24],[42,51],[42,84])
student_marks_arr=np.array(student_marks)
student_marks_arr+=(5,10)
print(student_name)
print(student_marks_arr)

['ram', 'sihi', 'kruti', 'vedha']
[[47 58]
 [81 34]
 [47 61]
 [47 94]]


In [12]:
import numpy as np
arr = np.linspace(0,10)
print(arr)
print('length of arr:',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
length of arr: 50


In [13]:
import numpy as np
student_name = ['ram', 'sihi', 'kruti', 'vedha']
student_marks=([42,48],[76,24],[42,51],[42,84])
student_marks_arr=np.array(student_marks)
print(student_name)
print(student_marks_arr)



['ram', 'sihi', 'kruti', 'vedha']
[[42 48]
 [76 24]
 [42 51]
 [42 84]]


In [1]:
import numpy as np
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [7]:
import numpy as np
np.arange(0,10,3)

array([0, 3, 6, 9])

In [4]:
import numpy as np
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
print('sorted array:',np.sort(horsepower_arr))
print('original array after sorting:', horsepower_arr)

original array:  [130 165 150 150 140]
sorted array: [130 140 150 150 165]
original array after sorting: [130 165 150 150 140]


In [5]:
import numpy as np
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
print('original array after sorting:', horsepower_arr)

original array:  [130 165 150 150 140]
original array after sorting: [130 165 150 150 140]


In [10]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
filter_arr = horsepower_arr > 135
newarr = horsepower_arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True  True  True  True]
[165 150 150 140]


In [11]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >=150)
print(x)
horsepower_arr[x]




(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [10]:
students_marks = np.array([[67,45],[90,92],[66,72],[32,40]])
students_marks += [5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [6]:
import numpy as np 
step_walk=([[1,5243],[1,9424],[4,7145],[1,4528],[4,8744],[7,1185],[4,4824],[7,4581],[7,1494],[4,5446]])
step_walk=np.array(step_walk)
print(step_walk)

[[   1 5243]
 [   1 9424]
 [   4 7145]
 [   1 4528]
 [   4 8744]
 [   7 1185]
 [   4 4824]
 [   7 4581]
 [   7 1494]
 [   4 5446]]


In [7]:
day_num=[1,2,3,4,5,6,7,8,9,10]
step_walk=[4825,7414,4728,4287,7224,7688,4521,7712,8735,2828]
new_arr=np.array([day_num,step_walk])
print(new_arr)
print(day_num)
print(step_walk)

[[   1    2    3    4    5    6    7    8    9   10]
 [4825 7414 4728 4287 7224 7688 4521 7712 8735 2828]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[4825, 7414, 4728, 4287, 7224, 7688, 4521, 7712, 8735, 2828]


In [4]:

import numpy as np
step_walk=([[1,4825],[2,7414],[3,4728],[4,4287],[5,7224],[6,7688],[7,4521],[8,7712],[9,8735],[10,2828]])
step_walk=np.array(step_walk)
step_walk+=(0,2000)
print(step_walk)

[[    1  6825]
 [    2  9414]
 [    3  6728]
 [    4  6287]
 [    5  9224]
 [    6  9688]
 [    7  6521]
 [    8  9712]
 [    9 10735]
 [   10  4828]]


In [6]:

newarr=np.sort(step_walk)
print(newarr)

[[    1  6825]
 [    2  9414]
 [    3  6728]
 [    4  6287]
 [    5  9224]
 [    6  9688]
 [    7  6521]
 [    8  9712]
 [    9 10735]
 [   10  4828]]


In [1]:
new_arr= arr[:,1] + 2000
arr[:,1]=new_arr
arr

NameError: name 'arr' is not defined

In [7]:
import numpy as np
day_number=np.arange(1,11)
steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr = np.array([day_number, steps_walked])
arr = arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [8]:
matched = arr[:,1]>9000
matched
new_arr = arr[matched]
new_arr

array([[  10, 9569]])

In [9]:
sortedArr = arr[arr[:,1].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

Sorted 2D Numpy Array
[[   5 4598]
 [   6 5564]
 [   1 6012]
 [   3 6886]
 [   7 6971]
 [   2 7079]
 [   4 7230]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [10]:
import numpy as np
arr = np.array([[1, 2],[3, 4]])
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
             



10
[4 6]
[3 7]


In [11]:
arr=np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [15]:
arr= np.array([[1,2],[3,4]])
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))

4
[3 4]
[2 4]


In [17]:
print(np.min(arr))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

1
[1 2]
[1 3]


In [2]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [3]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.prod(arr))
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))

24
[3 8]
[ 2 12]


In [4]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))

1.118033988749895
[1. 1.]
[0.5 0.5]


In [5]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.var(arr))
print(np.var(arr, axis=0))
print(np.var(arr, axis=1))

1.25
[1. 1.]
[0.25 0.25]


In [6]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [8]:
import numpy as np
arr1 = np.array([4,5,6])
arr2 = np.array([1,2,3])
result = arr1 - arr2
print(result)

[3 3 3]


In [9]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [11]:
import numpy as np
arr1 = np.array([4,6,8])
arr2 = np.array([2,3,4])
result = arr1 / arr2
print(result)

[2. 2. 2.]


In [13]:
import numpy as np
arr = np.array([2,3,4])
result = arr ** 2
print(result)

[ 4  9 16]


In [15]:
import numpy as np
arr = np.array([4,9,16])
result = np.sqrt(arr)
print(result)

[2. 3. 4.]


In [16]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
result = arr1 == arr2
print(result)

[ True  True  True]


In [20]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean)
print(result_std)
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [22]:
import numpy as np
arr = np.array([2.3, 4.7, 6.1])
result = np.round(arr)
print(result)

[2. 5. 6.]


In [24]:
import numpy as np
arr = np.array([2,3,4])
result = np.power(arr,2)
print(result)

[ 4  9 16]


In [25]:
import numpy as np
arr = np.array([1,5,10])
result = np.where(arr < 5, arr, 0)
print(result)

[1 0 0]


In [26]:
import numpy as np
arr = np.array([1,2,3,4,5])
result = np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


In [27]:
import numpy as np
arr = np.array([3,1,4,2,5])
result = np.sort(arr)
print(result)

[1 2 3 4 5]


In [10]:
import numpy as np
S_X = np.array([[2, 5, 6, 5],[4, 8, 6, 5]])
S_Y = np.array([[6, 7, 5, 9],[7, 5, 6, 4]])
quarterly_difference = S_Y - S_X
print(quarterly_difference)



[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [11]:
less_than_2 = S_X < 2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [18]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
#[[ 2 7 13 18] 
#[ 4 12 18 23]]
print ( X_cumsum >= 8)
# [[False False True True]
#  [False True True True]]
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
#[[6 13 18 27]
# [7 12 18 22]print ( Y_cumsum >= 8)
# [[False True True True]
#  [False True True True]]
yearly_mean_X = np.mean(S_X, axis=1)
print(yearly_mean_X)

[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[4.5  5.75]


In [21]:
quarterly_mean_Y = np.mean(S_Y, axis=0)
print(quarterly_mean_Y)

[6.5 6.  5.5 6.5]


In [22]:
numbers = [1, 2, 3, 4, 5]
# Squaring each number using map()
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [23]:
numbers = [1, 2, 3, 4, 5]
# Filtering even number using filter()
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4]


In [25]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]
# Summing all the numbers using reduce()
sum_of_numbers = reduce (lambda x, y: x+y,numbers)
print(sum_of_numbers)

15


In [26]:
# Squaring a number using a lambda function
square = lambda x: x ** 2
print(square(5))

25
